######################################################################
##
## Filename: bus_subsystem_tb.udo
## Created on: Thu Nov 19 20:42:49 GMT Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
