######################################################################
##
## Filename: system86_tb.udo
## Created on: Wed Nov 18 22:37:59 GMT Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
